name: Update Themes
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chmod 755 ./.github/build.sh
          ./.github/build.sh

      - name: Zip Folder
        run: |
          zip -r themes.zip explore.tar.xz
          zip -r themes.zip lrone.tar.xz

      - name: export file size
        run: |
          mv ./.github/filesize ./filesize
          echo "explore_file_size=`ls -l ./explore.tar.xz | awk '{print $5}'`" >> ./filesize
          echo "lrone_file_size=`ls -l ./lrone.tar.xz | awk '{print $5}'`" >> ./filesize

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: pzcn
          author_email: pdzzzcn@gmail.com
          message: 'Update Themes'
          add: "['*.tar.xz', 'filesize']"